server:
  port: 5000

  spring:
  datasource:
    username: root
    password: 1215
    url: jdbc:mysql://localhost:3306/ocean_nest_hotel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

